name:    Minimal
version: "0.0.0"

dependencies:
- base
- yesod-core
- yesod >= 1.6.1.0
- text >= 1.2.4.0
- time >= 1.9.3
- http-conduit >= 2.3.7.4
- yesod-auth >= 1.6.10.1

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  Minimal:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Minimal
